### ISSUE TITLE
First iteration of cone recognizer.

### ISSUE THREAD

**Issue by mwimble** [victoriarobotics/victoria_perception#2]
Given an image frame, respond with a message indicating:

Was cone found?
Left/right position in frame, if found.
Rough distance to cone, if found.
Quality indication. E.g., poor quality if multiple candidate cones found, or cone size is very small, or image shape is suspect.
Suggested method:

If necessary, downsample frame.
Maybe erode/dilate to remove noise.
Maybe blur.
Maybe kmeans to find interesting HSL partitions that might contain code.
HSL thresholding to find cone object.
Find contiguous interesting blob pixels.
Determine if blob has interesting shape.
Compute l/r offset in frame, ideally in degrees from center frame (needs camera info).
Estimate distance based on height or width or both.
Compute general information about detection quality (maybe). E.g., if means indicates several possible cone blobs, indicate poor quality.
The intention is that the recognizer is invoked relatively infrequently as it is probably slow. Use the recognizer to compute an orientation and speed to be used to move the robot and to advise if the cone is close enough to

Stop using GPS-only movements to get near the cone.
Stop using camera-based movements to get near the cone and invoke the move-to-touch goal.

**Comment by griswaldbrooks** [comment]
Pictures of the cone from the r200.
The left and right angles are about 35 degrees, which is expected as the FOV is about 70 degrees horizontal. All of these measurements will have a deviation of several inches.

![center_0_ft](https://cloud.githubusercontent.com/assets/390783/23538681/071737f6-ff8a-11e6-83eb-951af2b68b18.jpg)
0 feet (touching)

![center_1_ft](https://cloud.githubusercontent.com/assets/390783/23538679/0715b26e-ff8a-11e6-8c6a-1155147a82c6.jpg)
1 foot

![center_2_ft](https://cloud.githubusercontent.com/assets/390783/23538680/07171ce4-ff8a-11e6-8657-da9ab02d174c.jpg)
2 feet

![center_4_ft](https://cloud.githubusercontent.com/assets/390783/23538682/07232b2e-ff8a-11e6-91c8-0c1deacc5044.jpg)
4 feet

![center_8_ft](https://cloud.githubusercontent.com/assets/390783/23538684/072570aa-ff8a-11e6-9190-9ba57fddedfb.jpg)
8 feet
![center_16_ft](https://cloud.githubusercontent.com/assets/390783/23538683/07252776-ff8a-11e6-9863-1f98fa2acfbc.jpg)
16 feet

![center_32_ft](https://cloud.githubusercontent.com/assets/390783/23538685/0725d0b8-ff8a-11e6-977a-c7de94a2d460.jpg)
32 feet

![robot_turned_left_16_ft](https://cloud.githubusercontent.com/assets/390783/23538686/072d83b2-ff8a-11e6-94e4-489a0ec1c8cb.jpg)
16 feet, robot turned left

![robot_turned_right_16_ft](https://cloud.githubusercontent.com/assets/390783/23538678/0714435c-ff8a-11e6-86c6-6399cec9e8a6.jpg)
16 feet, robot turned right

**Comment by mwimble** [comment]
<img width="1177" alt="16feetleftimage" src="https://cloud.githubusercontent.com/assets/11037919/23586118/bd2f2d86-0143-11e7-9f43-e84b4a3d0245.png">
An example of the first iteration of the cone recognizer. With the cone at the left of the frame at about 16 feet out, the cone is recognized at x: 48, y: 584 with a pixel area of 5221 square pixels.

**Comment by griswaldbrooks** [comment]
First version is checked in.
